spring.application.name=safariwave-backend

spring.datasource.url=jdbc:mysql://localhost:3306/safariwave_db
spring.datasource.username=root
spring.datasource.password=Vishmi@2147

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=8f42a73054b1749f8f58848be5e6502c526649c31c9a6f1a1b3fb42f0d0d59a
jwt.expiration=86400000